version: "3.9"

services:

  db:
    image: mysql:8.0
    container_name: maritime_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: maritime_portal
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  backend:
    build: ./grievance-backend
    container_name: maritime_backend
    volumes:
      - ./grievance-backend:/app
      - /app/node_modules
    ports:
      - "5000:3000"
    command: npm run dev
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: maritime_portal
      DB_PORT: 3306
      JWT_SECRET: maritime_secret_key_2026
    depends_on:
      - db

  frontend:
    build: ./grievance-frontend
    container_name: maritime_frontend
    volumes:
      - ./grievance-frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: npm run dev
    environment:
      VITE_API_URL: http://192.168.21.43:5000/api
    depends_on:
      - backend

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: maritime_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root